### ISSUE TITLE
Read Buffer and not Window Local Variables

### ISSUE THREAD

**Issue by Konfekt** [inkarkat/vim-DeleteTrailingWhitespace#1]
In

https://github.com/inkarkat/vim-DeleteTrailingWhitespace/blob/0dce6b97aeaedade37b0b37c37a3e176f8a14a8e/autoload/DeleteTrailingWhitespace.vim#L101

according to

```vim
" autoload/ingo/plugin/setting.vim (lines 80-85)
function! ingo#plugin#setting#GetBufferLocal( variableName, ... )
    return call('ingo#plugin#setting#GetFromScope', [a:variableName, ['b', 'g']] + a:000)
endfunction
function! ingo#plugin#setting#GetWindowLocal( variableName, ... )
    return call('ingo#plugin#setting#GetFromScope', [a:variableName, ['w', 'g']] + a:000)
endfunction
```
a window-local variable prefixed by `w:...` is read. Document is though a buffer-local variable prefixed by `b:...`

**Comment by inkarkat** [comment]
That was a mistake; thanks for noticing, Enno!
